#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtk-vnc
Version  : 0.9.0
Release  : 7
URL      : https://download.gnome.org/sources/gtk-vnc/0.9/gtk-vnc-0.9.0.tar.xz
Source0  : https://download.gnome.org/sources/gtk-vnc/0.9/gtk-vnc-0.9.0.tar.xz
Summary  : A GTK2 widget for VNC clients
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: gtk-vnc-bin
Requires: gtk-vnc-data
Requires: gtk-vnc-lib
Requires: gtk-vnc-license
Requires: gtk-vnc-locales
Requires: gtk-vnc-man
BuildRequires : buildreq-gnome
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(x11)
BuildRequires : pulseaudio-dev

%description
gtk-vnc is a VNC viewer widget for GTK2. It is built using coroutines
allowing it to be completely asynchronous while remaining single threaded.

%package bin
Summary: bin components for the gtk-vnc package.
Group: Binaries
Requires: gtk-vnc-data
Requires: gtk-vnc-license
Requires: gtk-vnc-man

%description bin
bin components for the gtk-vnc package.


%package data
Summary: data components for the gtk-vnc package.
Group: Data

%description data
data components for the gtk-vnc package.


%package dev
Summary: dev components for the gtk-vnc package.
Group: Development
Requires: gtk-vnc-lib
Requires: gtk-vnc-bin
Requires: gtk-vnc-data
Provides: gtk-vnc-devel

%description dev
dev components for the gtk-vnc package.


%package lib
Summary: lib components for the gtk-vnc package.
Group: Libraries
Requires: gtk-vnc-data
Requires: gtk-vnc-license

%description lib
lib components for the gtk-vnc package.


%package license
Summary: license components for the gtk-vnc package.
Group: Default

%description license
license components for the gtk-vnc package.


%package locales
Summary: locales components for the gtk-vnc package.
Group: Default

%description locales
locales components for the gtk-vnc package.


%package man
Summary: man components for the gtk-vnc package.
Group: Default

%description man
man components for the gtk-vnc package.


%prep
%setup -q -n gtk-vnc-0.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536470304
%configure --disable-static --with-gtk=3.0 --without-sasl --disable-vala
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1536470304
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/gtk-vnc
cp COPYING.LIB %{buildroot}/usr/share/doc/gtk-vnc/COPYING.LIB
%make_install
%find_lang gtk-vnc

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gvnccapture

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GVnc-1.0.typelib
/usr/lib64/girepository-1.0/GVncPulse-1.0.typelib
/usr/lib64/girepository-1.0/GtkVnc-2.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/gtk-vnc-2.0/gtk-vnc.h
/usr/include/gtk-vnc-2.0/vncdisplay.h
/usr/include/gtk-vnc-2.0/vncdisplayenums.h
/usr/include/gtk-vnc-2.0/vncgrabsequence.h
/usr/include/gtk-vnc-2.0/vncimageframebuffer.h
/usr/include/gvnc-1.0/gvnc.h
/usr/include/gvnc-1.0/vncaudio.h
/usr/include/gvnc-1.0/vncaudioformat.h
/usr/include/gvnc-1.0/vncaudiosample.h
/usr/include/gvnc-1.0/vncbaseaudio.h
/usr/include/gvnc-1.0/vncbaseframebuffer.h
/usr/include/gvnc-1.0/vnccolormap.h
/usr/include/gvnc-1.0/vncconnection.h
/usr/include/gvnc-1.0/vncconnectionenums.h
/usr/include/gvnc-1.0/vnccursor.h
/usr/include/gvnc-1.0/vncframebuffer.h
/usr/include/gvnc-1.0/vncpixelformat.h
/usr/include/gvnc-1.0/vncutil.h
/usr/include/gvncpulse-1.0/gvncpulse.h
/usr/include/gvncpulse-1.0/vncaudiopulse.h
/usr/lib64/libgtk-vnc-2.0.so
/usr/lib64/libgvnc-1.0.so
/usr/lib64/libgvncpulse-1.0.so
/usr/lib64/pkgconfig/gtk-vnc-2.0.pc
/usr/lib64/pkgconfig/gvnc-1.0.pc
/usr/lib64/pkgconfig/gvncpulse-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgtk-vnc-2.0.so.0
/usr/lib64/libgtk-vnc-2.0.so.0.0.2
/usr/lib64/libgvnc-1.0.so.0
/usr/lib64/libgvnc-1.0.so.0.0.1
/usr/lib64/libgvncpulse-1.0.so.0
/usr/lib64/libgvncpulse-1.0.so.0.0.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/gtk-vnc/COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/gvnccapture.1

%files locales -f gtk-vnc.lang
%defattr(-,root,root,-)

